// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository/buffer.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "nova/domain/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIBufferRepository is a mock of IBufferRepository interface.
type MockIBufferRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIBufferRepositoryMockRecorder
}

// MockIBufferRepositoryMockRecorder is the mock recorder for MockIBufferRepository.
type MockIBufferRepositoryMockRecorder struct {
	mock *MockIBufferRepository
}

// NewMockIBufferRepository creates a new mock instance.
func NewMockIBufferRepository(ctrl *gomock.Controller) *MockIBufferRepository {
	mock := &MockIBufferRepository{ctrl: ctrl}
	mock.recorder = &MockIBufferRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBufferRepository) EXPECT() *MockIBufferRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIBufferRepository) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIBufferRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIBufferRepository)(nil).Delete), id)
}

// FindByID mocks base method.
func (m *MockIBufferRepository) FindByID(id int) (*model.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Buffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIBufferRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIBufferRepository)(nil).FindByID), id)
}

// List mocks base method.
func (m *MockIBufferRepository) List() ([]*model.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*model.Buffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIBufferRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIBufferRepository)(nil).List))
}

// Save mocks base method.
func (m *MockIBufferRepository) Save(buffer *model.Buffer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", buffer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIBufferRepositoryMockRecorder) Save(buffer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIBufferRepository)(nil).Save), buffer)
}

// Update mocks base method.
func (m *MockIBufferRepository) Update(buffer *model.Buffer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", buffer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIBufferRepositoryMockRecorder) Update(buffer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIBufferRepository)(nil).Update), buffer)
}
